name: macOS

on: [push, pull_request]

jobs:
  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: install
      run: brew install sdl2
    - name: configure
      run: mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang ..
    - name: build
      run: cd Release && make -j $(sysctl -n hw.ncpu)
